feat: add Elevation
determined-ai/hew pull request #13
Opened 2023-10-23 19:37 UTC by thiagodallacqua-hpe

## Description

Tickets: WEB-1673

Add `Elevation`to the UI kit.

## Test Plan

- Go to the `/design/#Elevation` page in order to check the new `Elevation` module examples

![Screen Shot 2023-10-27 at 15 44 28](https://github.com/determined-ai/determined-ui/assets/104855841/321397c0-f477-432d-8950-62641a5c9bb5)

![Screen Shot 2023-10-27 at 15 44 36](https://github.com/determined-ai/determined-ui/assets/104855841/660e015c-df62-42ba-9602-112aa30674d5)

## Commentary (optional)

## Checklist

- [ ] Changes have been manually QA'd
- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
  See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.

## Ticket

2023-10-23 19:51 UTC, EmilyBonar commented
My understanding was that we were handling elevation with background colors rather than box shadows, has that changed?

2023-10-26 13:55 UTC, EmilyBonar reviewed
Here are some notes

2023-10-26 13:55 UTC, EmilyBonar commented on src/DesignKit.tsx
> +        <br />
fix: All of these sections should be more clearly delineated with an <hr /> or bold titles, ideally both. Look at the Form section for an example

2023-10-26 13:55 UTC, EmilyBonar commented on src/DesignKit.tsx
> +        <br />
Oh lol I didn't realize it would render an `<hr />`

2023-10-26 13:55 UTC, EmilyBonar commented on src/DesignKit.tsx
> +        </Columns>
fix: these should just be in one container that wraps, like a Space. This applies to the other places you did this as well. Also, is it necessary to include the `{' ... '}` around the text?

2023-10-26 13:55 UTC, EmilyBonar commented on src/kit/Card.tsx
> +  );
nit: i think in this case useMemo probably adds more overhead than just doing `const themeStyle = ui.darkLight === DarkLight.Dark ? css.dark : css.light;`

2023-10-26 13:55 UTC, EmilyBonar commented on src/DesignKit.tsx
> +          base elevation without hover interaction (for elements elements at level 1)
nit: These example titles should be capitalized and bolded.
fix: duplicate "elements"
q: it seems like this elevation system doesn't really have a concept of levels anymore, so i'm not sure what "level 1" means here

2023-10-26 13:55 UTC, EmilyBonar commented on src/DesignKit.tsx
> +        <Paragraph>the hover state has the sabe bg color as the selected state2</Paragraph>
fix: "sabe" -> "same"
q: I don't know what state2 is referring to?

2023-10-26 13:55 UTC, EmilyBonar commented on src/DesignKit.tsx
> +  const cssSulfix = useMemo(
fix: It's spelled "suffix"

2023-10-26 13:55 UTC, EmilyBonar commented on src/DesignKit.tsx
> +        <Paragraph>tooltip-like element (with special contrast)</Paragraph>
nit: "tooltip-like" doesn't sound good in this context, especially since there isn't anything here specific to tooltips

2023-10-27 19:32 UTC, ClaireNeveu requested changes
An enum of elevations needs to be exported from the UI kit for use with components like `Surface`.

2023-10-27 19:32 UTC, ClaireNeveu commented on src/kit/Card.tsx
> +  const { ui } = useUI();
Changes to the card are a separate ticket.

2023-10-27 19:42 UTC, ClaireNeveu commented on src/DesignKit.tsx
> +  return (
You can just model this on the Icon section and list the 5 elevations in a row.

2023-10-30 16:36 UTC, ClaireNeveu approved these changes

2023-10-30 20:18 UTC, EmilyBonar approved these changes
Looks good, just a few small changes

2023-10-30 20:18 UTC, EmilyBonar commented on src/DesignKit.module.scss
fix: since elevation isn't getting a design kit section these changes can be reverted

2023-10-30 20:18 UTC, EmilyBonar commented on src/kit/Elevation/index.module.scss
> +      border: 2px solid var(--elevation-0-border-light);
fix: unless there's a specific reason to do otherwise these all should probably use `--theme-stroke-width` for border width

2023-10-31 13:35 UTC, merged